version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@firebase/rules-unit-testing"
    versions:
    - 1.1.10
    - 1.1.11
    - 1.2.0
    - 1.2.1
    - 1.2.10
    - 1.2.2
    - 1.2.3
    - 1.2.4
    - 1.2.5
    - 1.2.6
    - 1.2.7
    - 1.2.8
    - 1.2.9
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.1.9
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-a11y"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-storyshots"
    versions:
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.1.9
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.7
    - 6.2.8
  - dependency-name: "@nuxtjs/storybook"
    versions:
    - 3.3.1
    - 3.3.2
    - 4.0.0
    - 4.0.1
  - dependency-name: chromatic
    versions:
    - 5.6.1
    - 5.6.2
    - 5.6.3
    - 5.7.0
    - 5.7.1
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
    - 9.6.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
